
define audio.bmiamextend = "Audio/Berry/b miam extend.mp3"
define audio.bmiam = "Audio/Berry/b miam.mp3"
define audio.bbj = "Audio/Berry/b bj.mp3"
define audio.bhah = "Audio/Berry/bhah.mp3"
define audio.bcummouth = "Audio/Berry/b cummouth.mp3"
define audio.blol1 = "Audio/Berry/b lol1.mp3"
define audio.blol2 = "Audio/Berry/b lol2.mp3"
define audio.bhello = "Audio/Berry/b hello.mp3"
define audio.bcandy = "Audio/Berry/bcandy.mp3"
define audio.bcandy1 = "Audio/Berry/bcandy.mp3"
define audio.bcandy2 = "Audio/Berry/bcandy2.mp3"
define audio.bjesus1 = "Audio/Berry/bohjesus1.mp3"
define audio.bjesus2 = "Audio/Berry/bohjesus2.mp3"
define audio.bohjesus1 = "Audio/Berry/bohjesus1.mp3"
define audio.bohjesus2 = "Audio/Berry/bohjesus2.mp3"
define audio.bno1 = "Audio/Berry/b no1.ogg"
define audio.bow1 = "Audio/Berry/b ow.mp3"
define audio.bow = "Audio/Berry/b ow.mp3"
define audio.bow2 = "Audio/Berry/b ow2.mp3"
define audio.bsoulagement1 = "Audio/Berry/b soulagement.mp3"
define audio.bruok = "Audio/Berry/b r u ok.mp3"
define audio.bmoansp = "Audio/Berry/bmoansp.ogg"
define audio.bmoans1 = "Audio/Berry/bmoans1.ogg"
define audio.bmoans2 = "Audio/Berry/bmoans2.ogg"
define audio.bmoans3 = "Audio/Berry/bmoans3.ogg"
define audio.bnaughtyboy = "Audio/Berry/bnaughtyboy.ogg"
define audio.bkisstongue = "Audio/Berry/bkisstongue.ogg"
define audio.bdonttrytoholdback = "Audio/Berry/bdonttrytoholdback.ogg"
define audio.bgoodboy = "Audio/Berry/bgoodboy.ogg"
define audio.btjmoan = "Audio/Berry/btjmoan.ogg"
define audio.bcumgoodboy = "Audio/Berry/bcumgoodboy.ogg"
define audio.bsoperfect = "Audio/Berry/bsoperfect.ogg"
define audio.bdontmove = "Audio/Berry/bdontmove.ogg"
define audio.bcuminmouth = "Audio/Berry/bcuminmouth.ogg"

define audio.bdtyandere05loop = "Audio/Berry/bdtyandere05loop.ogg"
define audio.bmygoodboy = "Audio/Berry/bmygoodboy.ogg"
define audio.bcum1 = "Audio/Berry/bcum1.ogg"
define audio.bcumyeah = "Audio/Berry/bcumyeah.ogg"
define audio.bmoanshard = "Audio/Berry/bmoanshard.ogg"

define audio.eloser1 = "Audio/Emma/e loser1.mp3"
define audio.eloser2 = "Audio/Emma/e loser2.mp3"
define audio.eloser3 = "Audio/Emma/e loser3.mp3"
define audio.eno1 = "Audio/Emma/e no1.mp3"
define audio.eno2 = "Audio/Emma/e no2.mp3"
define audio.enoway1 = "Audio/Emma/e noway1.mp3"
define audio.enoway2 = "Audio/Emma/e noway2.mp3"
define audio.esoupir = "Audio/Emma/e soupir.mp3"
define audio.etsah = "Audio/Emma/e tsah.mp3"
define audio.ewhat1 = "Audio/Emma/e what1.mp3"
define audio.ewhat2 = "Audio/Emma/e what2.mp3"
define audio.eyes1 = "Audio/Emma/e yes1.mp3"
define audio.eyes2 = "Audio/Emma/e yes2.mp3"
define audio.eomg1 = "Audio/Emma/eomg1.mp3"
define audio.eomg2 = "Audio/Emma/eomg2.mp3"
define audio.eomg3 = "Audio/Emma/eomg3.mp3"
define audio.emoans1 = "Audio/Emma/emoans1.ogg"
define audio.emoans2 = "Audio/Emma/emoans2.ogg"
define audio.emoans3 = "Audio/Emma/emoans3.ogg"
define audio.emoans4 = "Audio/Emma/emoans4.ogg"
define audio.emoans5 = "Audio/Emma/emoans5.ogg"
define audio.emoanssoft = "Audio/Emma/emoanssoft.ogg"
define audio.emoansingle = "Audio/Emma/emoansingle.ogg"
define audio.edontstop = "Audio/Emma/edontstop.ogg"
define audio.ecum1 = "Audio/Emma/ecum1.ogg"
define audio.ecum2 = "Audio/Emma/ecum2.ogg"
define audio.ecum3 = "Audio/Emma/ecum3.ogg"
define audio.ekiss = "Audio/Emma/ekiss.ogg"
define audio.ecuminmouth = "Audio/Emma/ecuminmouth.ogg"
define audio.ecuminmouth2 = "Audio/Emma/ecuminmouth2.ogg"
define audio.ebj = "Audio/Emma/ebj.ogg"
define audio.edt_2 = "Audio/Emma/edt_2.ogg"
define audio.edt_1wet = "Audio/Emma/edt_1wet.ogg"
define audio.edt_2wet = "Audio/Emma/edt_2wet.ogg"

define audio.sha = "Audio/Sarena/s ha.ogg"
define audio.slol1 = "Audio/Sarena/s lol1.mp3"
define audio.snani1 = "Audio/Sarena/s nani1.mp3"
define audio.sno = "Audio/Sarena/s no.mp3"
define audio.sowh = "Audio/Sarena/s owh.mp3"
define audio.ssurprise = "Audio/Sarena/s surprise.mp3"
define audio.syeah1 = "Audio/Sarena/s yeah1.mp3"
define audio.syeah2 = "Audio/Sarena/s yeah2.mp3"
define audio.shm = "Audio/Sarena/shm.mp3"
define audio.smoh1 = "Audio/Sarena/smoh1.mp3"
define audio.smoh2 = "Audio/Sarena/smoh2.mp3"
define audio.spony = "Audio/Sarena/spony.mp3"
define audio.shey2 = "Audio/Sarena/shey2.mp3"
define audio.shey1 = "Audio/Sarena/shey1.mp3"
define audio.sthink = "Audio/Sarena/sthink.mp3"
define audio.souaw1 = "Audio/Sarena/souaw1.mp3"
define audio.souaw2 = "Audio/Sarena/souaw2.mp3"
define audio.sdontmove = "Audio/Sarena/sdontmove.ogg"
define audio.sifeelsogood = "Audio/Sarena/sifeelsogood.ogg"
define audio.ssoftmoans = "Audio/Sarena/ssoftmoans.ogg"
define audio.ssurprised = "Audio/Sarena/ssurprised.ogg"
define audio.sdt2sec = "Audio/Sarena/sdt2sec.ogg"
define audio.skiss = "Audio/Sarena/skiss.ogg"

define audio.smoans1 = "Audio/Sarena/smoans1.ogg"
define audio.shardmoans2ample = "Audio/Sarena/shardmoans2ample.ogg"
define audio.sbj69cum = "Audio/Sarena/sbj69cum.ogg"
define audio.sbj69 = "Audio/Sarena/sbj69.ogg"
define audio.scum2 = "Audio/Sarena/scum2.ogg"
define audio.shardmoans1 = "Audio/Sarena/shardmoans1.ogg"
define audio.sbjcum = "Audio/Sarena/sbjcum.ogg"
define audio.sbjhard = "Audio/Sarena/sbjhard.ogg"
define audio.sbjsoft = "Audio/Sarena/sbjsoft.ogg"
define audio.scum1 = "Audio/Sarena/scum1.ogg"
define audio.ssoftmoans2 = "Audio/Sarena/ssoftmoans2.ogg"
define audio.snani1 = "Audio/Sarena/s nani1.mp3"




define audio.vbrat = "Audio/Valerie/vbrat.mp3"
define audio.vhah = "Audio/Valerie/vhah.mp3"
define audio.vhoh = "Audio/Valerie/vhoh.mp3"
define audio.vholyfuck1 = "Audio/Valerie/vholyfuck1.mp3"
define audio.vholyfuck2 = "Audio/Valerie/vholyfuck2.mp3"
define audio.vmoansp1 = "Audio/Valerie/vmoansp1.ogg"
define audio.vmoansp2 = "Audio/Valerie/vmoansp2.ogg"
define audio.vmoans1 = "Audio/Valerie/vmoans1.ogg"
define audio.vmoanshj = "Audio/Valerie/vmoanshj.ogg"
define audio.vmccum = "Audio/Valerie/vmccum.ogg"
define audio.vmoanstj = "Audio/Valerie/vmoanstj.ogg"
define audio.vsleep = "Audio/Valerie/vsleep.ogg"
define audio.vcum1 = "Audio/Valerie/vcum1.ogg"
define audio.vmoanssex1 = "Audio/Valerie/vmoanssex1.ogg"
define audio.vmoanslick = "Audio/Valerie/vmoanslick.ogg"
define audio.vmoans2 = "Audio/Valerie/vmoans2.ogg"
define audio.vmoansdrunk = "Audio/Valerie/vmoansdrunk.ogg"
define audio.vdt2s = "Audio/Valerie/vdt2s.ogg"
define audio.vdt1s = "Audio/Valerie/vdt1s.ogg"
define audio.vdt05s = "Audio/Valerie/vdt05s.ogg"
define audio.vcuminmouth = "Audio/Valerie/vcuminmouth.ogg"
define audio.vbj = "Audio/Valerie/vbj.ogg"
define audio.vtousse = "Audio/Valerie/vtousse.ogg"
define audio.vcuminthroat = "Audio/Valerie/vcuminthroat.ogg"
define audio.vcomeback = "Audio/Valerie/vcomeback.ogg"

define audio.zmoans = "Audio/Zoe/zmoans.ogg"
define audio.zlol = "Audio/Zoe/z lol.mp3"
define audio.zcum1 = "Audio/Zoe/zcum1.ogg"

define audio.zuh = "Audio/Zoe/zuh.mp3"


define audio.hit = "Audio/Generic/hit.mp3"
define audio.hh = "Audio/Generic/hh.ogg"
define audio.doublegrab = "Audio/Generic/doubleattrapage.ogg"
define audio.claque1 = "Audio/Generic/claque1.mp3"
define audio.fightfast = "Audio/Generic/fight fast.ogg"

define audio.chillsexy = "Audio/Musics/chill sexy.ogg"
define audio.jigsaw = "Audio/Musics/jigsaw_puzzle.ogg"
define audio.jigsaw_puzzle = "Audio/Musics/jigsaw_puzzle.ogg"
define audio.main = "Audio/Musics/main.ogg"
define audio.sand_castle = "Audio/Musics/sand_castle.ogg"
define audio.robot_boogie = "Audio/Musics/robot_boogie.ogg"
define audio.sunny_day = "Audio/Musics/sunny_day.ogg"
define audio.Wutif = "Audio/Musics/Wutif.ogg"
define audio.papapalapa = "Audio/Musics/papapalapa.ogg"
define audio.causmic = "Audio/Musics/causmic.ogg"
define audio.storm = "Audio/Generic/storm.ogg"
define audio.Extreme = "Audio/Musics/extreme.mp3"
define audio.funnydinner = "Audio/Musics/funny dinner.mp3"
define audio.Harpe = "Audio/Musics/Harpe.mp3"
define audio.Goal = "Audio/Musics/Goal.mp3"
define audio.Moon_magic = "Audio/Musics/Moon_magic.mp3"

define audio.main = "Audio/Musics/main.ogg"


define audio.cunni = "Audio/sexfx/sexfx cunnis.mp3"
define audio.bj = "Audio/sexfx/bj add.mp3"
define audio.frottements = "Audio/sexfx/frottements.mp3"
define audio.frottements2 = "Audio/sexfx/frottements2.ogg"
define audio.bjcum = "Audio/sexfx/sons ejac inside.mp3"
define audio.bj50 = "Audio/sexfx/bj add 50speed.mp3"
define audio.spank = "Audio/Generic/claque1.mp3"
define audio.sex05 = "Audio/sexfx/sex05wet.ogg"
define audio.sex05b = "Audio/sexfx/sex05.ogg"
define audio.sex025 = "Audio/sexfx/sex025wet.ogg"
define audio.sex033 = "Audio/sexfx/sex033wet.ogg"
define audio.sex066 = "Audio/sexfx/sex066wet.ogg"
define audio.sex10 = "Audio/sexfx/sex10wet.ogg"
define audio.sex10b = "Audio/sexfx/sex10.ogg"
define audio.sex20 = "Audio/sexfx/sex20wet.ogg"
define audio.tjdemi = "Audio/sexfx/tjdemi.ogg"
define audio.cumsound = "Audio/sexfx/cumsound.ogg"
define audio.cumsoundext = "Audio/sexfx/cumsoundext.ogg"
define audio.cumexplo = "Audio/sexfx/cumexplo.ogg"
define audio.sex05wet = "Audio/sexfx/sex05wet.ogg"
define audio.sex025wet = "Audio/sexfx/sex025wet.ogg"
define audio.sex033wet = "Audio/sexfx/sex033wet.ogg"
define audio.sex066wet = "Audio/sexfx/sex066wet.ogg"
define audio.sex10wet = "Audio/sexfx/sex10wet.ogg"
define audio.sex20wet = "Audio/sexfx/sex20wet.ogg"
define audio.pulsation2 = "Audio/sexfx/pulsation2.ogg"


define audio.acum1 = "Audio/sexfx/acum1.ogg"
define audio.acum2 = "Audio/sexfx/acum2.ogg"
define audio.acum3 = "Audio/sexfx/acum3.ogg"

define audio.dt1 = "Audio/sexfx/dt1.ogg"
define audio.dt1_7 = "Audio/sexfx/dt1_7.ogg"
define audio.dt2 = "Audio/sexfx/dt2.ogg"
define audio.dt1_33 = "Audio/sexfx/dt1_33.ogg"
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
