
define blvhintfree = ["Berry works in her room.","It's party time!",
    "Take a visit to Berry while she is working in her room.",
    "Spy again on Berry while she is working in her room!", "",
    "Buy her an new cosplay outfit at the PC. Give it to her when she works in her room.",
    "Find her in the kitchen",
    "Join her at 10 P.M at the hallway.",
    "Don't forget to checkout her new daily life events. \nBerry needs you when she's in her room!",
    "Berry is looking at her feedback at the backyard",
    "Try to contact Isabelle on the internet.",
    "Tell Berry she can talk with her idol! In her room.",
    "Spend the night with Berry at the living room",
    "Don't forget to checkout her new daily life events. \nGo to sleep after getting a call with Zoe. (In your room at 10 PM)",
    "Break up with Zoe. Just pass the day.",
    "Let her wake you up.",
    "She is expecting a package delivery.",
    "You can hear some noises from her room when she's working.",
    "The beast will come for you. Pass the day.",
    "You have finished Berry's individual storyline, congratulations! Don't forget to checkout her new daily life events."]

define slvhintfree = ["Sarena works at the balcony.",
    "It's party time!",
    "Propose Sarena to make videos when she's at the balcony.",
    "Ask her about the video's feedback, at the backyard.",
    "Time to make another video with Sarena! At the Balcony.",
    "Pass the day.",
    "Meet Sarena at the balcony.",
    "It's time to do another video! At the Balcony.",
    "Don't forget to checkout her new daily life events. \nSarena is in the kitchen? What is she doing?",
    "Sarena is having a discussion with her girlfriend in her room at the evening.",
    "It's maybe time to make a new video! At the Balcony.",
    "Sarena is in the kitchen? What is she doing?",
    "Am I fantasizing about Sarena? Anyway, time to go to sleep.",
    "Find her on the map.",
    "You can hear Sarena from the living room.",
    "Sarena is preparing something, when will it happen? Pass the day.",
    "Don't forget to checkout her new daily life events. \nGo to sleep after getting a call with Zoe. (In your room at 10 PM)",
    "Break up with Zoe. Just pass the day.",
    "Annonce your break-up to Sarena at the backyard.",
    "Wait for something to happen. Just pass the day.",
    "Make an other video with her! At the balcony.",
    "Wait for her to call for you. Just pass the day.",
    "You have finished Sarena's individual storyline, congratulations! Don't forget to checkout her new daily life events."]

define elvhintfree = ["Emma works at the computer.","It's party time!",
    "Meet Emma when she is streaming.","Meet Emma at the diningroom","Learn how to take photos on the internet.",
    "Propose her to try your new skills at the dinning-room","Find her at the backyard.","Join Emma at her room.",
    "Don't forget to checkout her new daily life events. \nGo the the PC when Emma is streaming.",
    "Emma is in her room, what is she doing?",
    "Emma is giving a call to her BF in the morning in her room.",
    "Wait for her to do something. Just pass the time.",
    "Wait for her to do something. Just pass the time.",
    "Don't forget to checkout her new daily life events. \nGo to sleep after getting a call with Zoe. (In your room at 10 PM)",
    "Break up with Zoe. Just pass the day.",
    "Emma is in her room in the morning!",
    "Emma is in Valerie's room around 6 PM",
    "Wait for her to do something when you wake-up. Just pass the time.",
    "Emma is in her room around 2 PM!",
    "Wait for her to do something when you go to sleep. Just pass the time.",
    "You have finished Emma's individual storyline, congratulations! Don't forget to checkout her new daily life events."]
define vlvhintfree = ["Valerie works in her room.","It's party time!",
    "Find an interesting moment.",
    "Find a way to get fake sperm.",
    "Give her the \"fake\" sperm.",
    "Valerie is preparing something...",
    "Get your revenge while she's not paying attention.",
    "Shower when she passes at 6 PM",
    "Wait for her to take action. Just pass the time.",
    "Don't forget to checkout her new daily life events. \nSpy on her once again.",
    "Steal her dildo right before she starts to work. In her room at 6PM",
    "Some noise is coming from your room, in the afternoon.",
    "You have an idea but you need a toolkit (on the internet), then go to your room.",
    "Show her your work when she's in her room.",
    "It's show time. In her room.",
    "Don't forget to checkout her new daily life events. \nGo to sleep after getting a call with Zoe. (In your room at 10 PM)",
    "Break up with Zoe. Just pass the day.",
    "Valerie is doing something in her room in the evening.",
    "Valerie is doing something in her room in the evening.",
    "Wait for a call. Pass the time.",
    "Talk to Valerie at the backyard",
    "Wait for her. Pass the time.",
    "You have finished Valerie's individual storyline, congratulations! Don't forget to checkout her new daily life events."]
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
